[package]
name = "p2p-network"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.41", features = ["full"]}
serde = {version = "1.0", features = ["derive"]}
postcard = { version = "1.1", features = ["alloc"] }
thiserror = "2.0"
hex = "0.4"
async-trait = "0.1"
rand = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }